### ISSUE TITLE
docs.sixlabors.com domain not resolving

### ISSUE THREAD

**Issue by natehitze** [SixLabors/docs#25]
https://www.nslookup.io/dns-records/docs.sixlabors.com

**Comment by tocsoft** [comment]
@JimBobSquarePants looks like its DNS for the entire `sixlabors.com` domain.

**Comment by JimBobSquarePants** [comment]
Thanks for the heads up @natehitze I've repointed the DNS records. Just waiting now for it all to flow through

**Comment by JimBobSquarePants** [comment]
Looks like everything is up and running again. 

Can someone please confirm and I'll close this if so.

**Comment by natehitze** [comment]
It's working again for me, thanks!
