### ISSUE TITLE
Documentation about rxy is not clear, and sample querystring is wrong(?).

### ISSUE THREAD

**Issue by ErikHen** [SixLabors/docs#29]
Hi. Thank you for all the work you do with this library.
I wanted to use the rxy querystring when cropping images, but couldn't get it to work.
(https://github.com/SixLabors/docs/blob/master/articles/imagesharp.web/processingcommands.md/).
The sample code is "&rxy=30,30". But it's not clear in the documentation if that is pixels or percentage, or something else.
After some testing it seems that the values should actually be between 0-1. So, the sample querystring should be "&rxy=0.30,0.30" if you want the anchor point to be 30% top and 30% left?

I'm happy to do a PR to update the docs (provided I'm not wrong 😊).

**Comment by JimBobSquarePants** [comment]
Yep. You're absolutely correct! It should be a scale between 0-1.
